---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2024-01-08 - 13:53:41 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 23.0.4
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator
  namespace: {{ .Release.Namespace }}
