apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: kustomize-helm-plugin
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: quay.io/argoproj/argocd:v2.12.6
          imagePullPolicy: IfNotPresent
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: kustomize-helm-plugin
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - name: kustomize-helm-plugin
          configMap:
            name: kustomize-helm-plugin
        - emptyDir: {}
          name: cmp-tmp

