apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ch11/configmanagementplugins
    repoURL: https://github.com/sabre1041/argocd-up-and-running-book
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
