---

setupGitea: true
setupScriptFile: files/setup_gitea.sh
scriptsMountPath: /etc/scripts

gitea:
  deployment:
    env:
      - name: GITEA__webhook__ALLOWED_HOST_LIST
        value: "argocd.upandrunning.local, tekton-triggers-argocd.upandrunning.local"
      - name: GITEA__webhook__SKIP_TLS_VERIFY
        value: "true"
  scheme: http
  host: gitea-http
  port: 3000
  admin: {}
