apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- golist-api-config.yaml
- golist-api-service.yaml
- golist-api-deployment.yaml
- golist-api-ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"connection_string":"golist:golist@tcp(database-mariadb:3306)/golist","port":8080}'
  target:
    kind: ConfigMap
    name: golist-api-config
    version: v1
