apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golist-api
  namespace: argocd
spec:
  source:
    path: ch08/apps/golist-api
    repoURL: 'https://github.com/sabre1041/argocd-up-and-running-book'
    targetRevision: main
  destination:
    namespace: golist
    server: 'https://kubernetes.default.svc'
  project: golist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
