{{- if .Values.setupGitea }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.setupFullName" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
data:
  GITEA_SCHEME: {{ .Values.gitea.scheme | b64enc }}
  GITEA_HOST: {{ .Values.gitea.host | b64enc }}
  GITEA_PORT: {{ .Values.gitea.port | toString | b64enc }}
  GITEA_USERNAME: {{ (.Values.gitea.admin.username | default .Values.gitea.gitea.admin.username) | b64enc }}
  GITEA_PASSWORD: {{ (.Values.gitea.admin.password | default .Values.gitea.gitea.admin.password) | b64enc }}
{{- end }}
