apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: golist
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - description: Developers get view and sync
    name: golist-developer
    policies:
    - p, proj:golist:golist-developer, applications, get, golist/*, allow
    - p, proj:golist:golist-developer, applications, sync, golist/*, allow
    groups:
    - Developers
