---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: mattermost-operator
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mattermost-operator
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: docker.io/bitnami/minio:2024
        ports:
        - containerPort: 9000
        - containerPort: 9001
        imagePullPolicy: Always
        env:
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "https://minio.upandrunning.local/minio/"
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "adminadmin"
        - name: MINIO_DEFAULT_BUCKETS
          value: "mattermost"
        volumeMounts:
        - name: minio-storage
          mountPath: "/data"
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: mattermost-operator
spec:
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  type: ClusterIP
---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost-operator
spec:
  imagePullPolicy: IfNotPresent
  version: 5.28.0
  size: 100users
  useServiceLoadBalancer: false
  ingress:
    enabled: true
    host: mattermost.upandrunning.local
  mattermostEnv:
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
  licenseSecret: ""
  database:
    external:
      secret: mm-db-credentials
  fileStore:
    external:
      url: minio-service.mattermost-operator.svc.cluster.local:9000
      bucket: mattermost
      secret: file-store-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: mm-db-credentials
  namespace: mattermost-operator
type: Opaque
data:
  DB_CONNECTION_STRING: cG9zdGdyZXM6Ly9tYXR0ZXJtb3N0Om1hdHRlcm1vc3RAbWF0dGVybW9zdC1vcGVyYXRvci1wb3N0Z3Jlc3FsLm1hdHRlcm1vc3Qtb3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9tYXR0ZXJtb3N0P2Nvbm5lY3RfdGltZW91dD0xMCZzc2xtb2RlPWRpc2FibGU=
---
apiVersion: v1
kind: Secret
metadata:
  name: file-store-credentials
  namespace: mattermost-operator
type: Opaque
data:
  accesskey: YWRtaW4=
  secretkey: YWRtaW5hZG1pbg==
...
