apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- golist-frontend-config.yaml
- golist-frontend-deployment.yaml
- golist-frontend-ingress.yaml
- golist-frontend-service.yaml

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"api": "http://golist-api.7f000001.nip.io/api/products"}'
  target:
    kind: ConfigMap
    name: golist-frontend-config
    version: v1
