apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
