apiVersion: v1
kind: Service
metadata:
  labels:
    app: pricelist
    tier: frontend
  name: pricelist
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pricelist
    tier: frontend
status:
  loadBalancer: {}
