apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kustomize-helm.fullname" . }}
  labels:
    {{- include "kustomize-helm.labels" . | nindent 4 }}
data:
  baseValue: "{{ .Values.baseValue }}"
