apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ch13-simplego
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/christianh814/simple-go
    targetRevision: main
    path: deploy/overlays/default
  destination:
    namespace: ch13-apps
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
