apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.instances }}
  db:
    vendor: postgres
    host: {{ .Values.postgresql.name }}
    usernameSecret:
      name: {{ .Values.postgresql.secret.name }}
      key: username
    passwordSecret:
      name: {{ .Values.postgresql.secret.name }}
      key: password
  ingress:
    annotations:
      {{- tpl (toYaml .Values.ingress.annotations) . | nindent 6 }}
    className: {{ .Values.ingress.className }}
  http:
    tlsSecret: {{ .Values.ingress.tls.secret.name }}
  hostname:
    hostname: {{ .Values.ingress.host }}
