{{- $cert := .Files.Get .Values.ingress.tls.secret.cert -}}
{{- $key := .Files.Get .Values.ingress.tls.secret.key -}}
{{- if or (not $cert) (not $key) }}
{{ fail "Unable to locate Keycloak Ingress Certificate or Private Key" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt:  {{ $cert | b64enc }}
  tls.key: {{ $key | b64enc }}
