apiVersion: v1
kind: Secret
stringData:
  username: {{ .Values.postgresql.secret.username }}
  password: {{ .Values.postgresql.secret.password }}
metadata:
  name: {{ .Values.postgresql.secret.name }}
  namespace: {{ .Release.Namespace }}
